# Generated by Django 3.0.4 on 2020-04-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='time_of_order',
        ),
    ]
