# Generated by Django 3.0.4 on 2020-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200401_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_order',
            field=models.TimeField(auto_now=True),
        ),
    ]
